import { createSlice, configureStore } from "@reduxjs/toolkit";

const authSlice = createSlice({
  name: "auth", // Provide a name for the slice
  initialState: {
    user: "",
    isLoggedIn: false,
  },
  reducers: {
    // Example reducers
    login(state) {
      state.isLoggedIn = true;
    },
    logout(state) {
      state.user = "";
      state.isLoggedIn = false;
    },
  },
});

// Export the actions generated by createSlice
export const authActions = authSlice.actions;

// Create the store and add the reducer for this slice
export const store = configureStore({
  reducer: {
    auth: authSlice.reducer, // Assign the auth slice reducer
  },
});